INSERT INTO ASSINANTE (NOME) VALUES ('Luiz');
INSERT INTO ASSINANTE (NOME) VALUES ('Henrique');

INSERT INTO VEICULO (TIPO_VEICULO) VALUES ('CARRO');
INSERT INTO VEICULO (TIPO_VEICULO) VALUES ('MOTO');